[project]
name = "valkey-realtime-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "testcontainers>=4.13.2",
    "valkey-glide>=2.1.1",
]
